runtime: nodejs18
instance_class: F1
entrypoint: |
  npm install
  npm run app

runtime_config:
  operating_system: ubuntu22

automatic_scaling:
  target_cpu_utilization: 0.90
  min_instances: 1
  max_instances: 3
  min_pending_latency: 800ms
  max_pending_latency: automatic
  max_concurrent_requests: 80

resources:
  cpu: 4
  memory_gb: 4
  disk_size_gb: 10